### ISSUE TITLE
Client side crash bug

### ISSUE THREAD

**Issue by magnashake** [PippleCultist/HoloCureMultiplayerMod#10]
If the host drops a stamp, clients crash when walking on it, despite it being invisible to them.
Also, clients can't drop stamps, not sure if it's intentional.
![holocure multiplayer stamp crash log](https://github.com/user-attachments/assets/a60ce9ca-51b4-4a65-a6bd-39a4cdb768c0)

**Comment by PippleCultist** [comment]
This is now fixed in v1.1.5
