### ISSUE TITLE
Error Running Mod

### ISSUE THREAD

**Issue by shenjien** [PippleCultist/HoloCureMultiplayerMod#15]
I'm running into this error when trying to run the game with the mod:

############################################################################################
ERROR in
action number 1
of Create Event
for object obj_TitleScreen:

Creating instance for non-existing object: -1
0> CallbackManagerMod!_AurieFrameworkInit+0x1C632
1> HoloCure+0x22308B9
2> HoloCure+0x21A73A1
3> YYToolkit!ModuleUnload+0x61AE
4> YYToolkit!ModuleUnload+0x5EDD
5> HolocureMultiplayerMod!_AurieFrameworkInit+0x16F69
6> CallbackManagerMod!_AurieFrameworkInit+0xC13
7> YYToolkit!ModuleUnload+0x1D4BB
8> YYToolkit!ModuleUnload+0x1C685
9> HoloCure+0x2158963
10> HoloCure+0x22CA8F5
11> HoloCure+0x22B1BFB
12> HoloCure+0x220ACFE
13> HoloCure+0x2208371
14> HoloCure+0x2209BE2
15> HoloCure+0x22363EB
16> HoloCure+0x242542E
17> KERNEL32!BaseThreadInitThunk+0x1D
18> ntdll!RtlUserThreadStart+0x28
############################################################################################

Is there a fix?

**Comment by PippleCultist** [comment]
Closing because the issue was AurieLoader not being properly installed due to Windows Defender.
