### ISSUE TITLE
Game crashes if you try to use an ability

### ISSUE THREAD

**Issue by JIuCeHoK228** [PippleCultist/HoloCureMultiplayerMod#18]
It just crashes if you try to use special 
Here is the log:
___________________________________________
############################################################################################
ERROR in
action number 1
of Step Event1
for object input_controller_object:

(null) argument 1 incorrect type (array) expecting a Number (YYGI32)
0> CallbackManagerMod!_AurieFrameworkInit+0x2D056
1> HoloCure+0x215BF03
2> HoloCure+0x219114B
3> HolocureMultiplayerMod!ModuleInitialize+0x38C84
4> CallbackManagerMod!_AurieFrameworkInit+0x2E5B
5> CallbackManagerMod!_AurieFrameworkInit+0x7CB8
6> HoloCure+0x2154ABC
7> HoloCure+0x1D45A7E
8> HolocureMultiplayerMod!ModuleInitialize+0x12F8E
9> HolocureMultiplayerMod!_AurieFrameworkInit+0x1BCB8
10> CallbackManagerMod!_AurieFrameworkInit+0x254E
11> YYToolkit!ModuleUnload+0x1D4BB
12> YYToolkit!ModuleUnload+0x1C685
13> HoloCure+0x2158963
14> HoloCure+0x22CA8F5
15> HoloCure+0x22B1BFB
16> HoloCure+0x22B1A0D
17> HoloCure+0x22FF787
18> HoloCure+0x2208500
19> HoloCure+0x22081E3
20> HoloCure+0x2209B8A
21> HoloCure+0x22363EB
22> HoloCure+0x242542E
23> KERNEL32!BaseThreadInitThunk+0x14
24> ntdll!RtlUserThreadStart+0x21
############################################################################################
gml_Script_ExecuteSpecialAttack_gml_Object_obj_InputManager_Create_0 (line 144)

**Comment by PippleCultist** [comment]
This issue should be fixed in v1.1.8
