### ISSUE TITLE
Menu Mod Not Launching Properly

### ISSUE THREAD

**Issue by Construct-8** [PippleCultist/HoloCureMultiplayerMod#20]
Every time I boot the game it seems like nothing happens, and this is all that's in the log.

2024_11_17_05_46_26 Holocure Multiplayer Mod v1.2.0 - Failed to get HoloCure Menu interface. Make sure that HoloCureMenuMod is located in the mods/Aurie directory.

![image](https://github.com/user-attachments/assets/16d2c749-6014-4fb6-be9b-311010abfe37)

**Comment by PippleCultist** [comment]
Did you download the HoloCureMenuMod from the multiplayer mod release? Also, make sure that you didn't accidentally disable it in AurieManager

**Comment by Construct-8** [comment]
I downloaded all of them fresh with the update, yes. And I can confirm in Aurie that it's enabled. I can try redownloading the mod again.

**Comment by Construct-8** [comment]
Well, I don't know why, but redownloading it worked? I deleted all the DLLs I had so I guess I just got a corrupted download? Just a problem on my end, so I'll close it.
