### ISSUE TITLE
Crashes due to certain character skills

### ISSUE THREAD

**Issue by HeSLHoG** [PippleCultist/HoloCureMultiplayerMod#22]
In my time playing with my friend today I have found at least 3 different issues with crashes due to certain character skills. All of the crashes happened specifically for my friend who was the host during this time.

First issue: One of Luna's skills or her weapon caused a crash after some time of use (Not when I picked up the upgrade). Here are the logs:

___________________________________________
############################################################################################
ERROR in action number 1
of Step Eventobj_Enemy for object obj_Attack:
Unable to get variable Nanora from object 00000249116E3800
0> CallbackManagerMod_1_!_AurieFrameworkInit+0x2D056
1> HoloCure+0x37379A3
2> HolocureMultiplayerMod_1_!_AurieFrameworkInit+0x2FF79
3> HoloCure+0xC83583
4> HoloCure+0x3723798
5> HoloCure+0x1082D94
6> HoloCure+0x3723798
7> HoloCure+0x1077F89
8> CallbackManagerMod_1_!_AurieFrameworkInit+0x2FFA
9> CallbackManagerMod_1_!_AurieFrameworkInit+0x7F58
10> HoloCure+0x3723798
11> HoloCure+0xAB6C98
12> HoloCure+0x3723798
13> HoloCure+0xAB561B
14> CallbackManagerMod_1_!_AurieFrameworkInit+0x2FFA
15> CallbackManagerMod_1_!_AurieFrameworkInit+0x7CE8
16> HoloCure+0x3723798
17> HoloCure+0xABECAF
18> HoloCure+0x3725ED9
19> YYToolkit!ModuleUnload+0x1E794
20> YYToolkit!ModuleUnload+0x1DEBC
21> CallbackManagerMod_1_!_AurieFrameworkInit+0x2701
22> YYToolkit!ModuleUnload+0x1D4BB
23> YYToolkit!ModuleUnload+0x1C685
24> HoloCure+0x3725963
25> HoloCure+0x390AE6A
26> HoloCure+0x38B45F7
27> HoloCure+0x38B43FD
28> HoloCure+0x3799C9B
29> HoloCure+0x3797F4F
30> HoloCure+0x37C7E56
############################################################################################
gml_Script_anon@26954@gml_Object_obj_AttackController_Other_11 (line 1045)
gml_Script_ApplyOnHitEffects@gml_Object_obj_BaseMob_Create_0 (line 714)
gml_Script_TakeDamage@gml_Object_obj_BaseMob_Create_0 (line 483)
gml_Script_HitTarget@gml_Object_obj_Attack_Create_0 (line 60)
gml_Script_OnCollideWithTarget@gml_Object_obj_Attack_Create_0 (line 36)
gml_Object_obj_Attack_Collision_obj_BaseMob (line 11)

Second issue: One of Watame's skills (I think) caused a crash after some time of use (Not when I picked up the upgrade). Here are the logs:

___________________________________________
############################################################################################
ERROR in action number 1
of Step Event0 for object obj_BaseMob:
Unable to get variable GiriWaru from object 000001AD504CFA00
0> CallbackManagerMod_1_!_AurieFrameworkInit+0x2D056
1> HoloCure+0x37379A3
2> HolocureMultiplayerMod_1_!_AurieFrameworkInit+0x2FF79
3> HoloCure+0x2AFA066
4> HoloCure+0x3723798
5> HoloCure+0x10714C3
6> HoloCure+0x3723798
7> HoloCure+0x6B6D7C
8> HoloCure+0x2B0343F
9> HoloCure+0x3723798
10> HoloCure+0x10714C3
11> HoloCure+0x3723798
12> HoloCure+0x6B6D7C
13> HoloCure+0x2AFD43B
14> HoloCure+0x3723798
15> HoloCure+0x108C971
16> HoloCure+0x3725ED9
17> YYToolkit!ModuleUnload+0x1E794
18> YYToolkit!ModuleUnload+0x1DEBC
19> CallbackManagerMod_1_!_AurieFrameworkInit+0x2701
20> YYToolkit!ModuleUnload+0x1D4BB
21> YYToolkit!ModuleUnload+0x1C685
22> HoloCure+0x3725963
23> HoloCure+0x390AE6A
24> HoloCure+0x38B45F7
25> HoloCure+0x3754CC4
26> HoloCure+0x284A259
27> HoloCure+0x3725ED9
28> YYToolkit!ModuleUnload+0x1E794
29> YYToolkit!ModuleUnload+0x1DEBC
30> CallbackManagerMod_1_!_AurieFrameworkInit+0x2701
31> YYToolkit!ModuleUnload+0x1D4BB
32> YYToolkit!ModuleUnload+############################################################################################
gml_Script_anon@343002@anon@342276@___struct___6466@anon@342132@gml_Object_obj_PlayerManager_Other_22 (line 10742)
gml_Script_OnHeal@gml_Object_obj_BaseMob_Create_0 (line 359)
gml_Script_Heal (line 8)
gml_Script_anon@347230@anon@347136@gml_Object_obj_PlayerManager_Other_22 (line 10928)
gml_Script_OnHeal@gml_Object_obj_BaseMob_Create_0 (line 359)
gml_Script_Heal (line 8)
gml_Script_anon@344517@___struct___6469@anon@344237@gml_Object_obj_PlayerManager_Other_22 (line 10797)
gml_Object_obj_BaseMob_Step_0 (line 114)
gml_Object_obj_Player_Step_0 (line 26)

Third issue: 'An Ancient One' skill on Ina causes a crash upon picking up the upgrade. Can't provide you with logs, since my friend already left, sorry. I will try and post logs for this issue tomorrow (Using 'Tomorrow' here is quite ironic, since this crash is related to Ina).

**Comment by HeSLHoG** [comment]
Update: I tried testing Ina's 'An Ancient One' with my other friend and it doesn't seem to cause any crashes at all (We tested both Ina player being host and Ina player being joinee). So I am not really sure what caused this crash, I can only say that this crash happened to us more than once, everytime it crashed upon my friend (Who was always the host) picking up 'An Ancient One'

**Comment by PippleCultist** [comment]
The issues with Luna and Watame's skills causing crashes should be fixed in 1.2.1. I couldn't replicate the issue with Ina's Ancient One skill causing crashes, so hopefully the fixes I made also fixed that issue as well.
