### ISSUE TITLE
Unable to see the multiplayer option

### ISSUE THREAD

**Issue by Dragon718** [PippleCultist/HoloCureMultiplayerMod#26]
When I load up the mods, everything seems to work, however when I press play it takes me to character select rather than the multiplayer button. 
![image_2024-11-18_233855268](https://github.com/user-attachments/assets/25650d64-fc0a-4815-8c74-d811bac0e333)
![image_2024-11-18_233911398](https://github.com/user-attachments/assets/88c024e9-29c6-4a75-9518-7b69db6357ea)
![image_2024-11-18_233924224](https://github.com/user-attachments/assets/3e3ba292-3dc4-4b33-8f00-7a3b84f49b70)
![image_2024-11-18_233941582](https://github.com/user-attachments/assets/c47989c4-cc56-427f-9283-28c5303f1d7c)
![image_2024-11-18_233953556](https://github.com/user-attachments/assets/f8655253-6411-4a7c-b422-2ca95ac61417)
![image_2024-11-18_234003728](https://github.com/user-attachments/assets/0c4d7de6-4cd2-44fe-8cf6-e586978f0e7b)
![image_2024-11-18_234019146](https://github.com/user-attachments/assets/1cc6e0f3-393f-4232-b3ee-aa2f53de16b0)

**Comment by Dragon718** [comment]
All the logs are just completely blank. That's why I had to send screenshots

**Comment by Dragon718** [comment]
[2024_11_19_04_45_41.log](https://github.com/user-attachments/files/17809528/2024_11_19_04_45_41.log)
this is the only log that had anything, but its just one line

**Comment by PippleCultist** [comment]
Seems like it might be an issue with YYTK not working for the newest update HoloCure just got today. I've contacted the YYTK dev to see what's causing the issue.

**Comment by PippleCultist** [comment]
This issue should be gone after the latest update of HoloCure. The Aurie dev is looking into why it specifically wasn't working on the previous version.
