### ISSUE TITLE
Menu suffling around + crash on joining a stage

### ISSUE THREAD

**Issue by Scarlaid** [PippleCultist/HoloCureMultiplayerMod#30]
cant really tell what I did wrong here, the menu just go around rapidly and the game crash whenever I want to join a stage

https://github.com/user-attachments/assets/6b88cb21-4b7e-4a35-8087-e39c0ee9a4f8

**Comment by PippleCultist** [comment]
Judging from the log in your video, it looks like it's an issue with the discord rpc mod. Can you try disabling it and test with only the required mods for the multiplayer mod?

**Comment by Scarlaid** [comment]
>  it's an issue with the discord rpc mod
wow it was indeed is.... thanks 😭
