### ISSUE TITLE
registry key problem 

### ISSUE THREAD

**Issue by Globers233** [PippleCultist/HoloCureMultiplayerMod#33]
![Screenshot 2024-11-30 132517](https://github.com/user-attachments/assets/588eae0c-583c-45e8-94b4-f4eec2e4252c)

**Comment by Globers233** [comment]
how to fix it ?

**Comment by PippleCultist** [comment]
That's likely due to Windows Defender or your antivirus blocking AurieManager. You should whitelist it in order for it to work.
