### ISSUE TITLE
Trojan virus?

### ISSUE THREAD

**Issue by PaleoJafarius** [PippleCultist/HoloCureMultiplayerMod#34]
So i downloaded aurieloader.exe to play holocure with my friend (we're already at the last step), and then my windows defender deleted the aurieloader because there's a trojan virus detected. Specifically Trojan:Win32/Phonzy.A!ml. Any way to fix this?
![trojan moment](https://github.com/user-attachments/assets/db78b695-8cc1-4d9f-aacc-9d19cca0d044)
(Note : I actually dont know whether to put the issue in here or on the aurieframework site, sorry if im on the wrong site)

**Comment by PippleCultist** [comment]
That's because it would cost the Aurie dev a few hundred USD to sign AurieLoader.exe with a valid certificate to stop Windows Defender and antiviruses from marking it as a virus. The only solution right now is to whitelist AurieLoader.exe.
