### ISSUE TITLE
BL Fujoshi crashes on icon render

### ISSUE THREAD

**Issue by kd8lvt** [PippleCultist/HoloCureMultiplayerMod#4]
Characters: Korone (host & crashee), Ayame (client)  
Ingame Time: 18:54  
Crashee's Weapons:  
   * Psycho Axe 7
   * BL Book 7
   * Orayo! 7
   * Idol Concert 1
   * Stream of Tears 1  
   
Crashee's Items:  
  * Nephilim Soda 5
  * Idol Costume 5
  * Kusogaki's Shackles 3
  * Study Glasses 5
  * Chicken Feather 3
  * Sweet Candy 3 (The name eludes me. It's a Sweet Appetite reference)  

Crashee's Stamps:  
  * Greed 3
  * Bomb 1
  * Haste 3

Steps to reproduce:  
1. Meet the requirements to collab **Bl Book** and **Psycho Axe**
2. In a golden anvil, select **Psycho Axe** and then **BL Book** (that's the order I did it in, unsure if it matters)
3. Crash with the following log:
```
___________________________________________
############################################################################################
ERROR in
action number 1
of Draw Event
for object obj_PlayerManager:

I32 argument is undefined
0> CallbackManagerMod!_AurieFrameworkInit+0x1C632
1> HoloCure+0x21599A9
2> HoloCure+0x2157657
3> HoloCure+0x1C5BEE0
4> HoloCure+0x2158EE9
5> YYToolkit!ModuleUnload+0x1B974
6> YYToolkit!ModuleUnload+0x1B0AC
7> CallbackManagerMod!_AurieFrameworkInit+0xBF3
8> YYToolkit!ModuleUnload+0x1A6AB
9> YYToolkit!ModuleUnload+0x198A5
10> HoloCure+0x2158963
11> HoloCure+0x22CA8F5
12> HoloCure+0x22B1BFB
13> HoloCure+0x22B1A0D
14> HoloCure+0x229A6CB
15> HoloCure+0x2299FB6
16> HoloCure+0x2208229
17> HoloCure+0x2209B8A
18> HoloCure+0x22363EB
19> HoloCure+0x242542E
20> KERNEL32!BaseThreadInitThunk+0x1D
21> ntdll!RtlUserThreadStart+0x28
############################################################################################
gml_Object_obj_PlayerManager_Draw_64 (line 2111)
```

For some more context, I had the golden hammer but the client didn't, and I was unable to collab Idol Costume and Idol Concert? It might be related, idk,

**Comment by PippleCultist** [comment]
This is now fixed in v1.1.4.
