### ISSUE TITLE
Game crashing 6-7 mins in

### ISSUE THREAD

**Issue by Nottherealion** [PippleCultist/HoloCureMultiplayerMod#5]
Playing with only one extra person however the game crashes. Never made it past 10 mins yet as its crashes and gives the errors. Tried to host on both sides ( i hosted then she did) the same issue. Maybe something to do with items as i have noticed it crashes when we try to pick up items or accidentally touch a different character's items such as the painter's language bubbles if you are not the painter. ( we try to avoid it however sometimes one of us accidentally touches it ). The game crashes for regular items like the loot boxes too. 
___________________________________________
############################################################################################
ERROR in
action number 1
of  Step Eventobj_Player
for object obj_langOrb:

Unable to get variable Polyglot from object 000001963288D600
0> CallbackManagerMod!_AurieFrameworkInit+0x1C632
1> HoloCure+0x21576F0
2> HoloCure+0x1747A3C
3> HoloCure+0x2158EE9
4> YYToolkit!ModuleUnload+0x1B974
5> YYToolkit!ModuleUnload+0x1B0AC
6> CallbackManagerMod!_AurieFrameworkInit+0xBF3
7> YYToolkit!ModuleUnload+0x1A6AB
8> YYToolkit!ModuleUnload+0x198A5
9> HoloCure+0x2158963
10> HoloCure+0x22CA8F5
11> HoloCure+0x22B1BFB
12> HoloCure+0x22B1A0D
13> HoloCure+0x21C82CB
14> HoloCure+0x21C661F
15> HoloCure+0x2208774
16> HoloCure+0x22081E3
17> HoloCure+0x2209B8A
18> HoloCure+0x22363EB
19> HoloCure+0x242542E
20> KERNEL32!BaseThreadInitThunk+0x1D
21> ntdll!RtlUserThreadStart+0x28
############################################################################################
gml_Object_obj_langOrb_Collision_obj_Player (line 9)

**Comment by kd8lvt** [comment]
Characters and skills that also crash with a similar error:
* Mumei's Bloodthirst
* Zeta's Intelligence
Both crash when an enemy is killed.

**Comment by PippleCultist** [comment]
The issue with picking up Iofi's language orbs should be fixed in v1.1.2. @kd8lvt Can you create a separate issue with crash logs because I couldn't replicate the issues you're having.
