### ISSUE TITLE
Not Sure

### ISSUE THREAD

**Issue by Nick721l** [PippleCultist/HoloCureMultiplayerMod#9]
I'm not really sure if I'm just not understanding what to do, but I try to make a steam lobby and I'm just kinda stuck here 
![image_2024-07-01_104926162](https://github.com/PippleCultist/HoloCureMultiplayerMod/assets/174354441/972c5a09-89e2-44fa-b231-fe0725e5ee8f)

**Comment by PippleCultist** [comment]
Did you back out of the lobby and create a new one? It seems like there's a bug where players that join won't show up if that happens. I'll fix it in the next update, so just don't back out of the lobby for now until it's fixed.

**Comment by Nick721l** [comment]
ok I got it working somewhat, but I'm trying to play with 2 of my friends and when one joins the other can't

**Comment by Nick721l** [comment]
> Did you back out of the lobby and create a new one? It seems like there's a bug where players that join won't show up if that happens. I'll fix it in the next update, so just don't back out of the lobby for now until it's fixed.


ok I got it working somewhat, but I'm trying to play with 2 of my friends and when one joins the other can't
